"""Tests for generated artifact source inspection."""

from pathlib import Path

from pup_clean.inspect.generated import discover_generated_paths


def _write_source(root: Path, source: str) -> None:
    """Write a Python source file under the repository src directory."""
    package_dir = root / "src" / "example_project"
    package_dir.mkdir(parents=True)

    (package_dir / "main.py").write_text(
        source,
        encoding="utf-8",
    )


def test_discovers_generated_csv_literal_path(tmp_path: Path) -> None:
    """A CSV written by project source should be discovered."""
    _write_source(
        tmp_path,
        """
import pandas as pd

df = pd.DataFrame({"value": [1, 2, 3]})
df.to_csv("data/prepared/results.csv", index=False)
""",
    )

    paths = discover_generated_paths(tmp_path)

    assert paths == (Path("data/prepared/results.csv"),)


def test_discovers_generated_path_from_path_objects(tmp_path: Path) -> None:
    """Path constants and slash composition should be resolved."""
    _write_source(
        tmp_path,
        """
from pathlib import Path

import pandas as pd

DATA_DIR = Path("data")
PREPARED_DIR = DATA_DIR / "prepared"
OUTPUT_PATH = PREPARED_DIR / "sales_prepared.parquet"

df = pd.DataFrame({"value": [1, 2, 3]})
df.to_parquet(OUTPUT_PATH)
""",
    )

    paths = discover_generated_paths(tmp_path)

    assert paths == (Path("data/prepared/sales_prepared.parquet"),)


def test_discovers_generated_duckdb_database(tmp_path: Path) -> None:
    """A DuckDB database created by project source should be discovered."""
    _write_source(
        tmp_path,
        """
from pathlib import Path

import duckdb

DW_DIR = Path("data") / "dw"
DATABASE_PATH = DW_DIR / "sales.duckdb"

connection = duckdb.connect(DATABASE_PATH)
""",
    )

    paths = discover_generated_paths(tmp_path)

    assert paths == (Path("data/dw/sales.duckdb"),)


def test_discovers_generated_sqlite_database(tmp_path: Path) -> None:
    """A SQLite database created by project source should be discovered."""
    _write_source(
        tmp_path,
        """
from pathlib import Path
import sqlite3

DATABASE_PATH = Path("data") / "dw" / "sales.sqlite"

connection = sqlite3.connect(DATABASE_PATH)
""",
    )

    paths = discover_generated_paths(tmp_path)

    assert paths == (Path("data/dw/sales.sqlite"),)


def test_discovers_generated_image(tmp_path: Path) -> None:
    """An image explicitly generated by source code should be discovered."""
    _write_source(
        tmp_path,
        """
from pathlib import Path
import matplotlib.pyplot as plt

IMAGE_PATH = Path("docs") / "images" / "sales_by_region.png"

fig, ax = plt.subplots()
fig.savefig(IMAGE_PATH)
""",
    )

    paths = discover_generated_paths(tmp_path)

    assert paths == (Path("docs/images/sales_by_region.png"),)


def test_does_not_infer_other_images_in_same_directory(
    tmp_path: Path,
) -> None:
    """Only the exact image generated by source code should be discovered."""
    generated_image = tmp_path / "docs" / "images" / "sales_by_region.png"
    preserved_image = tmp_path / "docs" / "images" / "Fig1.png"

    generated_image.parent.mkdir(parents=True)

    generated_image.write_bytes(b"generated")
    preserved_image.write_bytes(b"preserved")

    _write_source(
        tmp_path,
        """
from pathlib import Path
import matplotlib.pyplot as plt

IMAGE_PATH = Path("docs") / "images" / "sales_by_region.png"

fig, ax = plt.subplots()
fig.savefig(IMAGE_PATH)
""",
    )

    paths = discover_generated_paths(tmp_path)

    assert Path("docs/images/sales_by_region.png") in paths
    assert Path("docs/images/Fig1.png") not in paths


def test_does_not_treat_read_path_as_generated(tmp_path: Path) -> None:
    """Input data read by the source should not be considered generated."""
    _write_source(
        tmp_path,
        """
from pathlib import Path
import pandas as pd

INPUT_PATH = Path("data") / "prepared" / "sales.csv"

df = pd.read_csv(INPUT_PATH)
""",
    )

    paths = discover_generated_paths(tmp_path)

    assert paths == ()


def test_input_and_output_paths_are_distinguished(tmp_path: Path) -> None:
    """The source operation, not the directory name, determines provenance."""
    _write_source(
        tmp_path,
        """
from pathlib import Path
import pandas as pd

INPUT_PATH = Path("data") / "prepared" / "sales.csv"
OUTPUT_PATH = Path("data") / "dw" / "sales.parquet"

df = pd.read_csv(INPUT_PATH)
df.to_parquet(OUTPUT_PATH)
""",
    )

    paths = discover_generated_paths(tmp_path)

    assert paths == (Path("data/dw/sales.parquet"),)


def test_dynamic_output_path_is_not_guessed(tmp_path: Path) -> None:
    """A path that cannot be resolved statically should not be returned."""
    _write_source(
        tmp_path,
        """
from pathlib import Path
import pandas as pd

name = get_output_name()
OUTPUT_PATH = Path("data") / "prepared" / f"{name}.csv"

df = pd.DataFrame({"value": [1, 2, 3]})
df.to_csv(OUTPUT_PATH, index=False)
""",
    )

    paths = discover_generated_paths(tmp_path)

    assert paths == ()


def test_returns_empty_tuple_without_src_directory(tmp_path: Path) -> None:
    """A repository without src should have no discovered source outputs."""
    paths = discover_generated_paths(tmp_path)

    assert paths == ()
